spring:
  datasource:
    url: jdbc:mysql://ranian.asuscomm.com:61616/TRIPLE?autoReconnect=true
    username: khangyh
    password: sQ6*1ocAsD
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
